### PR TITLE
Cowasy instead of print, Closes #2

### LINKED ISSUE #2: Use `cowsay` or a better template for showing the "PASTE -->" message

### PR DESCRIPTION
**Pull request by SepehrRasouli**
Hi @lnxpy, I added cowsay to pasteme-cli. This PR Closes #2.

### CODE REVIEW

**Comment by lnxpy** [comment]
Salam Sepehr jan. I didn't mean the actual [cowsay](https://pypi.org/project/cowsay/) to be clear. Since the only information we show is a simple link, that would be much cooler if we keep it a bit less fancy. Also it's in CLI.

**Comment by SepehrRasouli** [comment]
Hi Dear @lnxpy, Sorry for the misunderstanding, How can i fix it ? Did you mean to print out "COWASY ==>" instead of "PRINT ==>" ? Can you clarify ? 
Thank you :)

**Comment by lnxpy** [comment]
@SepehrRasouli Follow up #2 :)

**Comment by farhaduneci** [comment]
Good job on this one @SepehrRasouli :rocket:

**Comment by SepehrRasouli** [comment]
Hi @lnxpy, I changed the code a little bit, now the program can select a random logo from logos.py and choose them. I mostly chose Planets, But one of them is a Dragon :)

**Pull request closed without merging**
