### PR TITLE
Random Logo instead of 'PRINT', Closes #2

### LINKED ISSUE #2: Use `cowsay` or a better template for showing the "PASTE -->" message

### PR DESCRIPTION
**Pull request by SepehrRasouli**
Hi @lnxpy, The former PR got closed because of some conflicts.
This PR closes Issue #2 by automatically selecting one of the logos in logos.py file and showing it to the user.

### CODE REVIEW

**Comment by lnxpy** [comment]
Maybe something less fancy? They might break up the responsiveness though. We need something smaller, and cute at the same time. :)

**Comment by SepehrRasouli** [comment]
@lnxpy Thanks for you comment, What part of it do you think I should change ? Are the ASCII Arts too big ? Can you elaborate a little bit more ?

**Comment by lnxpy** [comment]
@SepehrRasouli We may need to either move on and never implement such a visual aspect or find a minimal collection that is hard to find.

**Comment by SepehrRasouli** [comment]
@lnxpy, We can gather a collection ourselves, the main problem is that I don't know what type, size and shape you want that collection to be, Can you give me some examples ?

**Comment by lnxpy** [comment]
@SepehrRasouli Galaxy-like shapes or astronomical objects. Not sure if we can find the thing that fits our requirements.

**Comment by SepehrRasouli** [comment]
Small Galaxy-like shapes can be found easily on ASCII Art websites, I will find some and make another commit, Let me now what you think about it.

**Comment by SepehrRasouli** [comment]
Closed as another PR will solve this.

**Pull request closed without merging**
